# Generated by Django 5.0.4 on 2024-11-14 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_likepublish_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratepublish',
            name='no_of_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ratepublish',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rater', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
