# Generated by Django 5.0.4 on 2024-11-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_customuser_username_channel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
