# Generated by Django 5.0.4 on 2024-11-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.FileField(blank=True, default='defaults/icons.png', max_length=255, null=True, upload_to=''),
        ),
    ]
