# Generated by Django 5.0.4 on 2024-11-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
