# Generated by Django 5.0.4 on 2024-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
