# Generated by Django 5.0.4 on 2024-12-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enable_notifications',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='make_profile_public',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_online_status',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_authentication',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
    ]
