# Generated by Django 5.0.4 on 2024-12-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_alter_profile_enable_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='two_factor_authentication',
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_auth_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_authentication',
            field=models.BooleanField(default=True),
        ),
    ]
