# Generated by Django 5.0.4 on 2024-12-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_remove_profile_two_factor_authentication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='two_factor_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
