# Generated by Django 5.0.4 on 2024-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_alter_customuser_two_factor_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_auth_code_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
