# Generated by Django 5.0.4 on 2024-12-07 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0020_customuser_two_factor_auth_code_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeInvest',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('likes', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Account.invest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_invest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RateInvest',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('no_of_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('rate', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='Account.invest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_invest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
